// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: messages.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message types
type MessageType int32

const (
	MessageType_UNKNOWN          MessageType = 0
	MessageType_INPUT            MessageType = 2
	MessageType_GAME_STATE       MessageType = 5
	MessageType_GAME_STATE_DELTA MessageType = 11
	MessageType_PLAYER_JOIN      MessageType = 6
	MessageType_PLAYER_LEAVE     MessageType = 7
	MessageType_PLAYER_RESPAWN   MessageType = 8
	MessageType_ERROR            MessageType = 10
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "UNKNOWN",
		2:  "INPUT",
		5:  "GAME_STATE",
		11: "GAME_STATE_DELTA",
		6:  "PLAYER_JOIN",
		7:  "PLAYER_LEAVE",
		8:  "PLAYER_RESPAWN",
		10: "ERROR",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":          0,
		"INPUT":            2,
		"GAME_STATE":       5,
		"GAME_STATE_DELTA": 11,
		"PLAYER_JOIN":      6,
		"PLAYER_LEAVE":     7,
		"PLAYER_RESPAWN":   8,
		"ERROR":            10,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

// Common structures
type Vector2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector2) Reset() {
	*x = Vector2{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2) ProtoMessage() {}

func (x *Vector2) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2.ProtoReflect.Descriptor instead.
func (*Vector2) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Vector2) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector2) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type InventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *InventoryItem) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *InventoryItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Player struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username                string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Position                *Vector2               `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Velocity                *Vector2               `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Lives                   float32                `protobuf:"fixed32,5,opt,name=lives,proto3" json:"lives,omitempty"`
	InvulnerableTimer       float64                `protobuf:"fixed64,13,opt,name=invulnerable_timer,json=invulnerableTimer,proto3" json:"invulnerable_timer,omitempty"`
	Score                   int32                  `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	Money                   int32                  `protobuf:"varint,7,opt,name=money,proto3" json:"money,omitempty"`
	Kills                   int32                  `protobuf:"varint,8,opt,name=kills,proto3" json:"kills,omitempty"`
	Rotation                float64                `protobuf:"fixed64,9,opt,name=rotation,proto3" json:"rotation,omitempty"`
	BulletsLeftByWeaponType map[string]int32       `protobuf:"bytes,10,rep,name=bullets_left_by_weapon_type,json=bulletsLeftByWeaponType,proto3" json:"bullets_left_by_weapon_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	NightVisionTimer        float64                `protobuf:"fixed64,11,opt,name=night_vision_timer,json=nightVisionTimer,proto3" json:"night_vision_timer,omitempty"`
	IsAlive                 bool                   `protobuf:"varint,12,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	Inventory               []*InventoryItem       `protobuf:"bytes,14,rep,name=inventory,proto3" json:"inventory,omitempty"`
	SelectedGunType         string                 `protobuf:"bytes,15,opt,name=selected_gun_type,json=selectedGunType,proto3" json:"selected_gun_type,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Player) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Player) GetVelocity() *Vector2 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *Player) GetLives() float32 {
	if x != nil {
		return x.Lives
	}
	return 0
}

func (x *Player) GetInvulnerableTimer() float64 {
	if x != nil {
		return x.InvulnerableTimer
	}
	return 0
}

func (x *Player) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Player) GetMoney() int32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *Player) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *Player) GetRotation() float64 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *Player) GetBulletsLeftByWeaponType() map[string]int32 {
	if x != nil {
		return x.BulletsLeftByWeaponType
	}
	return nil
}

func (x *Player) GetNightVisionTimer() float64 {
	if x != nil {
		return x.NightVisionTimer
	}
	return 0
}

func (x *Player) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

func (x *Player) GetInventory() []*InventoryItem {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *Player) GetSelectedGunType() string {
	if x != nil {
		return x.SelectedGunType
	}
	return ""
}

type Bullet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vector2               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Velocity      *Vector2               `protobuf:"bytes,3,opt,name=velocity,proto3" json:"velocity,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Damage        float32                `protobuf:"fixed32,5,opt,name=damage,proto3" json:"damage,omitempty"`
	IsEnemy       bool                   `protobuf:"varint,6,opt,name=is_enemy,json=isEnemy,proto3" json:"is_enemy,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	DeletedAt     int64                  `protobuf:"varint,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	InactiveMs    int64                  `protobuf:"varint,9,opt,name=inactive_ms,json=inactiveMs,proto3" json:"inactive_ms,omitempty"`
	WeaponType    string                 `protobuf:"bytes,8,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bullet) Reset() {
	*x = Bullet{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bullet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bullet) ProtoMessage() {}

func (x *Bullet) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bullet.ProtoReflect.Descriptor instead.
func (*Bullet) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Bullet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bullet) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Bullet) GetVelocity() *Vector2 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *Bullet) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Bullet) GetDamage() float32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *Bullet) GetIsEnemy() bool {
	if x != nil {
		return x.IsEnemy
	}
	return false
}

func (x *Bullet) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Bullet) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *Bullet) GetInactiveMs() int64 {
	if x != nil {
		return x.InactiveMs
	}
	return 0
}

func (x *Bullet) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

type Wall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vector2               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Width         float64                `protobuf:"fixed64,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,4,opt,name=height,proto3" json:"height,omitempty"`
	Orientation   string                 `protobuf:"bytes,5,opt,name=orientation,proto3" json:"orientation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wall) Reset() {
	*x = Wall{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wall) ProtoMessage() {}

func (x *Wall) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wall.ProtoReflect.Descriptor instead.
func (*Wall) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Wall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wall) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Wall) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Wall) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Wall) GetOrientation() string {
	if x != nil {
		return x.Orientation
	}
	return ""
}

type Enemy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vector2               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation      float64                `protobuf:"fixed64,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Lives         float32                `protobuf:"fixed32,4,opt,name=lives,proto3" json:"lives,omitempty"`
	WallId        string                 `protobuf:"bytes,5,opt,name=wall_id,json=wallId,proto3" json:"wall_id,omitempty"`
	IsDead        bool                   `protobuf:"varint,6,opt,name=is_dead,json=isDead,proto3" json:"is_dead,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enemy) Reset() {
	*x = Enemy{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enemy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enemy) ProtoMessage() {}

func (x *Enemy) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enemy.ProtoReflect.Descriptor instead.
func (*Enemy) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Enemy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Enemy) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Enemy) GetRotation() float64 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *Enemy) GetLives() float32 {
	if x != nil {
		return x.Lives
	}
	return 0
}

func (x *Enemy) GetWallId() string {
	if x != nil {
		return x.WallId
	}
	return ""
}

func (x *Enemy) GetIsDead() bool {
	if x != nil {
		return x.IsDead
	}
	return false
}

type Bonus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vector2               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	PickedUpBy    string                 `protobuf:"bytes,4,opt,name=picked_up_by,json=pickedUpBy,proto3" json:"picked_up_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bonus) Reset() {
	*x = Bonus{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bonus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bonus) ProtoMessage() {}

func (x *Bonus) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bonus.ProtoReflect.Descriptor instead.
func (*Bonus) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *Bonus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bonus) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Bonus) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Bonus) GetPickedUpBy() string {
	if x != nil {
		return x.PickedUpBy
	}
	return ""
}

type Shop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vector2               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shop) Reset() {
	*x = Shop{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shop) ProtoMessage() {}

func (x *Shop) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shop.ProtoReflect.Descriptor instead.
func (*Shop) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *Shop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shop) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

type InputMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Forward       bool                   `protobuf:"varint,1,opt,name=forward,proto3" json:"forward,omitempty"`
	Backward      bool                   `protobuf:"varint,2,opt,name=backward,proto3" json:"backward,omitempty"`
	Left          bool                   `protobuf:"varint,3,opt,name=left,proto3" json:"left,omitempty"`
	Right         bool                   `protobuf:"varint,4,opt,name=right,proto3" json:"right,omitempty"`
	Shoot         bool                   `protobuf:"varint,5,opt,name=shoot,proto3" json:"shoot,omitempty"`
	ItemKey       map[int32]bool         `protobuf:"bytes,6,rep,name=item_key,json=itemKey,proto3" json:"item_key,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputMessage) Reset() {
	*x = InputMessage{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputMessage) ProtoMessage() {}

func (x *InputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputMessage.ProtoReflect.Descriptor instead.
func (*InputMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *InputMessage) GetForward() bool {
	if x != nil {
		return x.Forward
	}
	return false
}

func (x *InputMessage) GetBackward() bool {
	if x != nil {
		return x.Backward
	}
	return false
}

func (x *InputMessage) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

func (x *InputMessage) GetRight() bool {
	if x != nil {
		return x.Right
	}
	return false
}

func (x *InputMessage) GetShoot() bool {
	if x != nil {
		return x.Shoot
	}
	return false
}

func (x *InputMessage) GetItemKey() map[int32]bool {
	if x != nil {
		return x.ItemKey
	}
	return nil
}

// Server -> Client messages
type GameStateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       map[string]*Player     `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Bullets       map[string]*Bullet     `protobuf:"bytes,2,rep,name=bullets,proto3" json:"bullets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Walls         map[string]*Wall       `protobuf:"bytes,3,rep,name=walls,proto3" json:"walls,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Enemies       map[string]*Enemy      `protobuf:"bytes,4,rep,name=enemies,proto3" json:"enemies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Bonuses       map[string]*Bonus      `protobuf:"bytes,5,rep,name=bonuses,proto3" json:"bonuses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Shops         map[string]*Shop       `protobuf:"bytes,7,rep,name=shops,proto3" json:"shops,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateMessage) Reset() {
	*x = GameStateMessage{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateMessage) ProtoMessage() {}

func (x *GameStateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateMessage.ProtoReflect.Descriptor instead.
func (*GameStateMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *GameStateMessage) GetPlayers() map[string]*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameStateMessage) GetBullets() map[string]*Bullet {
	if x != nil {
		return x.Bullets
	}
	return nil
}

func (x *GameStateMessage) GetWalls() map[string]*Wall {
	if x != nil {
		return x.Walls
	}
	return nil
}

func (x *GameStateMessage) GetEnemies() map[string]*Enemy {
	if x != nil {
		return x.Enemies
	}
	return nil
}

func (x *GameStateMessage) GetBonuses() map[string]*Bonus {
	if x != nil {
		return x.Bonuses
	}
	return nil
}

func (x *GameStateMessage) GetShops() map[string]*Shop {
	if x != nil {
		return x.Shops
	}
	return nil
}

func (x *GameStateMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GameStateDeltaMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UpdatedPlayers map[string]*Player     `protobuf:"bytes,1,rep,name=updated_players,json=updatedPlayers,proto3" json:"updated_players,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemovedPlayers []string               `protobuf:"bytes,2,rep,name=removed_players,json=removedPlayers,proto3" json:"removed_players,omitempty"`
	UpdatedBullets map[string]*Bullet     `protobuf:"bytes,3,rep,name=updated_bullets,json=updatedBullets,proto3" json:"updated_bullets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemovedBullets map[string]*Bullet     `protobuf:"bytes,4,rep,name=removed_bullets,json=removedBullets,proto3" json:"removed_bullets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedWalls   map[string]*Wall       `protobuf:"bytes,5,rep,name=updated_walls,json=updatedWalls,proto3" json:"updated_walls,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemovedWalls   []string               `protobuf:"bytes,6,rep,name=removed_walls,json=removedWalls,proto3" json:"removed_walls,omitempty"`
	UpdatedEnemies map[string]*Enemy      `protobuf:"bytes,7,rep,name=updated_enemies,json=updatedEnemies,proto3" json:"updated_enemies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemovedEnemies []string               `protobuf:"bytes,8,rep,name=removed_enemies,json=removedEnemies,proto3" json:"removed_enemies,omitempty"`
	UpdatedBonuses map[string]*Bonus      `protobuf:"bytes,9,rep,name=updated_bonuses,json=updatedBonuses,proto3" json:"updated_bonuses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemovedBonuses []string               `protobuf:"bytes,10,rep,name=removed_bonuses,json=removedBonuses,proto3" json:"removed_bonuses,omitempty"`
	UpdatedShops   map[string]*Shop       `protobuf:"bytes,12,rep,name=updated_shops,json=updatedShops,proto3" json:"updated_shops,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemovedShops   []string               `protobuf:"bytes,13,rep,name=removed_shops,json=removedShops,proto3" json:"removed_shops,omitempty"`
	Timestamp      int64                  `protobuf:"varint,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GameStateDeltaMessage) Reset() {
	*x = GameStateDeltaMessage{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateDeltaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateDeltaMessage) ProtoMessage() {}

func (x *GameStateDeltaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateDeltaMessage.ProtoReflect.Descriptor instead.
func (*GameStateDeltaMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *GameStateDeltaMessage) GetUpdatedPlayers() map[string]*Player {
	if x != nil {
		return x.UpdatedPlayers
	}
	return nil
}

func (x *GameStateDeltaMessage) GetRemovedPlayers() []string {
	if x != nil {
		return x.RemovedPlayers
	}
	return nil
}

func (x *GameStateDeltaMessage) GetUpdatedBullets() map[string]*Bullet {
	if x != nil {
		return x.UpdatedBullets
	}
	return nil
}

func (x *GameStateDeltaMessage) GetRemovedBullets() map[string]*Bullet {
	if x != nil {
		return x.RemovedBullets
	}
	return nil
}

func (x *GameStateDeltaMessage) GetUpdatedWalls() map[string]*Wall {
	if x != nil {
		return x.UpdatedWalls
	}
	return nil
}

func (x *GameStateDeltaMessage) GetRemovedWalls() []string {
	if x != nil {
		return x.RemovedWalls
	}
	return nil
}

func (x *GameStateDeltaMessage) GetUpdatedEnemies() map[string]*Enemy {
	if x != nil {
		return x.UpdatedEnemies
	}
	return nil
}

func (x *GameStateDeltaMessage) GetRemovedEnemies() []string {
	if x != nil {
		return x.RemovedEnemies
	}
	return nil
}

func (x *GameStateDeltaMessage) GetUpdatedBonuses() map[string]*Bonus {
	if x != nil {
		return x.UpdatedBonuses
	}
	return nil
}

func (x *GameStateDeltaMessage) GetRemovedBonuses() []string {
	if x != nil {
		return x.RemovedBonuses
	}
	return nil
}

func (x *GameStateDeltaMessage) GetUpdatedShops() map[string]*Shop {
	if x != nil {
		return x.UpdatedShops
	}
	return nil
}

func (x *GameStateDeltaMessage) GetRemovedShops() []string {
	if x != nil {
		return x.RemovedShops
	}
	return nil
}

func (x *GameStateDeltaMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PlayerJoinMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoinMessage) Reset() {
	*x = PlayerJoinMessage{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoinMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoinMessage) ProtoMessage() {}

func (x *PlayerJoinMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoinMessage.ProtoReflect.Descriptor instead.
func (*PlayerJoinMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerJoinMessage) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type PlayerLeaveMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeaveMessage) Reset() {
	*x = PlayerLeaveMessage{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeaveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeaveMessage) ProtoMessage() {}

func (x *PlayerLeaveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeaveMessage.ProtoReflect.Descriptor instead.
func (*PlayerLeaveMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerLeaveMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type PlayerRespawnMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRespawnMessage) Reset() {
	*x = PlayerRespawnMessage{}
	mi := &file_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRespawnMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRespawnMessage) ProtoMessage() {}

func (x *PlayerRespawnMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRespawnMessage.ProtoReflect.Descriptor instead.
func (*PlayerRespawnMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *PlayerRespawnMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Wrapper message
type GameMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GameMessage_Input
	//	*GameMessage_GameState
	//	*GameMessage_GameStateDelta
	//	*GameMessage_PlayerJoin
	//	*GameMessage_PlayerLeave
	//	*GameMessage_PlayerRespawn
	//	*GameMessage_Error
	Payload       isGameMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

func (x *GameMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *GameMessage) GetPayload() isGameMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameMessage) GetInput() *InputMessage {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *GameMessage) GetGameState() *GameStateMessage {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_GameState); ok {
			return x.GameState
		}
	}
	return nil
}

func (x *GameMessage) GetGameStateDelta() *GameStateDeltaMessage {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_GameStateDelta); ok {
			return x.GameStateDelta
		}
	}
	return nil
}

func (x *GameMessage) GetPlayerJoin() *PlayerJoinMessage {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_PlayerJoin); ok {
			return x.PlayerJoin
		}
	}
	return nil
}

func (x *GameMessage) GetPlayerLeave() *PlayerLeaveMessage {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_PlayerLeave); ok {
			return x.PlayerLeave
		}
	}
	return nil
}

func (x *GameMessage) GetPlayerRespawn() *PlayerRespawnMessage {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_PlayerRespawn); ok {
			return x.PlayerRespawn
		}
	}
	return nil
}

func (x *GameMessage) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGameMessage_Payload interface {
	isGameMessage_Payload()
}

type GameMessage_Input struct {
	Input *InputMessage `protobuf:"bytes,3,opt,name=input,proto3,oneof"`
}

type GameMessage_GameState struct {
	GameState *GameStateMessage `protobuf:"bytes,5,opt,name=game_state,json=gameState,proto3,oneof"`
}

type GameMessage_GameStateDelta struct {
	GameStateDelta *GameStateDeltaMessage `protobuf:"bytes,11,opt,name=game_state_delta,json=gameStateDelta,proto3,oneof"`
}

type GameMessage_PlayerJoin struct {
	PlayerJoin *PlayerJoinMessage `protobuf:"bytes,6,opt,name=player_join,json=playerJoin,proto3,oneof"`
}

type GameMessage_PlayerLeave struct {
	PlayerLeave *PlayerLeaveMessage `protobuf:"bytes,7,opt,name=player_leave,json=playerLeave,proto3,oneof"`
}

type GameMessage_PlayerRespawn struct {
	PlayerRespawn *PlayerRespawnMessage `protobuf:"bytes,8,opt,name=player_respawn,json=playerRespawn,proto3,oneof"`
}

type GameMessage_Error struct {
	Error *ErrorMessage `protobuf:"bytes,10,opt,name=error,proto3,oneof"`
}

func (*GameMessage_Input) isGameMessage_Payload() {}

func (*GameMessage_GameState) isGameMessage_Payload() {}

func (*GameMessage_GameStateDelta) isGameMessage_Payload() {}

func (*GameMessage_PlayerJoin) isGameMessage_Payload() {}

func (*GameMessage_PlayerLeave) isGameMessage_Payload() {}

func (*GameMessage_PlayerRespawn) isGameMessage_Payload() {}

func (*GameMessage_Error) isGameMessage_Payload() {}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\bprotocol\"%\n" +
	"\aVector2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"?\n" +
	"\rInventoryItem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\x9a\x05\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12-\n" +
	"\bposition\x18\x03 \x01(\v2\x11.protocol.Vector2R\bposition\x12-\n" +
	"\bvelocity\x18\x04 \x01(\v2\x11.protocol.Vector2R\bvelocity\x12\x14\n" +
	"\x05lives\x18\x05 \x01(\x02R\x05lives\x12-\n" +
	"\x12invulnerable_timer\x18\r \x01(\x01R\x11invulnerableTimer\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x05R\x05score\x12\x14\n" +
	"\x05money\x18\a \x01(\x05R\x05money\x12\x14\n" +
	"\x05kills\x18\b \x01(\x05R\x05kills\x12\x1a\n" +
	"\brotation\x18\t \x01(\x01R\brotation\x12k\n" +
	"\x1bbullets_left_by_weapon_type\x18\n" +
	" \x03(\v2-.protocol.Player.BulletsLeftByWeaponTypeEntryR\x17bulletsLeftByWeaponType\x12,\n" +
	"\x12night_vision_timer\x18\v \x01(\x01R\x10nightVisionTimer\x12\x19\n" +
	"\bis_alive\x18\f \x01(\bR\aisAlive\x125\n" +
	"\tinventory\x18\x0e \x03(\v2\x17.protocol.InventoryItemR\tinventory\x12*\n" +
	"\x11selected_gun_type\x18\x0f \x01(\tR\x0fselectedGunType\x1aJ\n" +
	"\x1cBulletsLeftByWeaponTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xc2\x02\n" +
	"\x06Bullet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.protocol.Vector2R\bposition\x12-\n" +
	"\bvelocity\x18\x03 \x01(\v2\x11.protocol.Vector2R\bvelocity\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12\x16\n" +
	"\x06damage\x18\x05 \x01(\x02R\x06damage\x12\x19\n" +
	"\bis_enemy\x18\x06 \x01(\bR\aisEnemy\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\x03R\tdeletedAt\x12\x1f\n" +
	"\vinactive_ms\x18\t \x01(\x03R\n" +
	"inactiveMs\x12\x1f\n" +
	"\vweapon_type\x18\b \x01(\tR\n" +
	"weaponType\"\x95\x01\n" +
	"\x04Wall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.protocol.Vector2R\bposition\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x01R\x06height\x12 \n" +
	"\vorientation\x18\x05 \x01(\tR\vorientation\"\xaa\x01\n" +
	"\x05Enemy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.protocol.Vector2R\bposition\x12\x1a\n" +
	"\brotation\x18\x03 \x01(\x01R\brotation\x12\x14\n" +
	"\x05lives\x18\x04 \x01(\x02R\x05lives\x12\x17\n" +
	"\awall_id\x18\x05 \x01(\tR\x06wallId\x12\x17\n" +
	"\ais_dead\x18\x06 \x01(\bR\x06isDead\"|\n" +
	"\x05Bonus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.protocol.Vector2R\bposition\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\fpicked_up_by\x18\x04 \x01(\tR\n" +
	"pickedUpBy\"E\n" +
	"\x04Shop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.protocol.Vector2R\bposition\"\x80\x02\n" +
	"\fInputMessage\x12\x18\n" +
	"\aforward\x18\x01 \x01(\bR\aforward\x12\x1a\n" +
	"\bbackward\x18\x02 \x01(\bR\bbackward\x12\x12\n" +
	"\x04left\x18\x03 \x01(\bR\x04left\x12\x14\n" +
	"\x05right\x18\x04 \x01(\bR\x05right\x12\x14\n" +
	"\x05shoot\x18\x05 \x01(\bR\x05shoot\x12>\n" +
	"\bitem_key\x18\x06 \x03(\v2#.protocol.InputMessage.ItemKeyEntryR\aitemKey\x1a:\n" +
	"\fItemKeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x80\a\n" +
	"\x10GameStateMessage\x12A\n" +
	"\aplayers\x18\x01 \x03(\v2'.protocol.GameStateMessage.PlayersEntryR\aplayers\x12A\n" +
	"\abullets\x18\x02 \x03(\v2'.protocol.GameStateMessage.BulletsEntryR\abullets\x12;\n" +
	"\x05walls\x18\x03 \x03(\v2%.protocol.GameStateMessage.WallsEntryR\x05walls\x12A\n" +
	"\aenemies\x18\x04 \x03(\v2'.protocol.GameStateMessage.EnemiesEntryR\aenemies\x12A\n" +
	"\abonuses\x18\x05 \x03(\v2'.protocol.GameStateMessage.BonusesEntryR\abonuses\x12;\n" +
	"\x05shops\x18\a \x03(\v2%.protocol.GameStateMessage.ShopsEntryR\x05shops\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x1aL\n" +
	"\fPlayersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.protocol.PlayerR\x05value:\x028\x01\x1aL\n" +
	"\fBulletsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.protocol.BulletR\x05value:\x028\x01\x1aH\n" +
	"\n" +
	"WallsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.protocol.WallR\x05value:\x028\x01\x1aK\n" +
	"\fEnemiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.protocol.EnemyR\x05value:\x028\x01\x1aK\n" +
	"\fBonusesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.protocol.BonusR\x05value:\x028\x01\x1aH\n" +
	"\n" +
	"ShopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.protocol.ShopR\x05value:\x028\x01\"\xc9\v\n" +
	"\x15GameStateDeltaMessage\x12\\\n" +
	"\x0fupdated_players\x18\x01 \x03(\v23.protocol.GameStateDeltaMessage.UpdatedPlayersEntryR\x0eupdatedPlayers\x12'\n" +
	"\x0fremoved_players\x18\x02 \x03(\tR\x0eremovedPlayers\x12\\\n" +
	"\x0fupdated_bullets\x18\x03 \x03(\v23.protocol.GameStateDeltaMessage.UpdatedBulletsEntryR\x0eupdatedBullets\x12\\\n" +
	"\x0fremoved_bullets\x18\x04 \x03(\v23.protocol.GameStateDeltaMessage.RemovedBulletsEntryR\x0eremovedBullets\x12V\n" +
	"\rupdated_walls\x18\x05 \x03(\v21.protocol.GameStateDeltaMessage.UpdatedWallsEntryR\fupdatedWalls\x12#\n" +
	"\rremoved_walls\x18\x06 \x03(\tR\fremovedWalls\x12\\\n" +
	"\x0fupdated_enemies\x18\a \x03(\v23.protocol.GameStateDeltaMessage.UpdatedEnemiesEntryR\x0eupdatedEnemies\x12'\n" +
	"\x0fremoved_enemies\x18\b \x03(\tR\x0eremovedEnemies\x12\\\n" +
	"\x0fupdated_bonuses\x18\t \x03(\v23.protocol.GameStateDeltaMessage.UpdatedBonusesEntryR\x0eupdatedBonuses\x12'\n" +
	"\x0fremoved_bonuses\x18\n" +
	" \x03(\tR\x0eremovedBonuses\x12V\n" +
	"\rupdated_shops\x18\f \x03(\v21.protocol.GameStateDeltaMessage.UpdatedShopsEntryR\fupdatedShops\x12#\n" +
	"\rremoved_shops\x18\r \x03(\tR\fremovedShops\x12\x1c\n" +
	"\ttimestamp\x18\v \x01(\x03R\ttimestamp\x1aS\n" +
	"\x13UpdatedPlayersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.protocol.PlayerR\x05value:\x028\x01\x1aS\n" +
	"\x13UpdatedBulletsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.protocol.BulletR\x05value:\x028\x01\x1aS\n" +
	"\x13RemovedBulletsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.protocol.BulletR\x05value:\x028\x01\x1aO\n" +
	"\x11UpdatedWallsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.protocol.WallR\x05value:\x028\x01\x1aR\n" +
	"\x13UpdatedEnemiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.protocol.EnemyR\x05value:\x028\x01\x1aR\n" +
	"\x13UpdatedBonusesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.protocol.BonusR\x05value:\x028\x01\x1aO\n" +
	"\x11UpdatedShopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.protocol.ShopR\x05value:\x028\x01\"=\n" +
	"\x11PlayerJoinMessage\x12(\n" +
	"\x06player\x18\x01 \x01(\v2\x10.protocol.PlayerR\x06player\"1\n" +
	"\x12PlayerLeaveMessage\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"3\n" +
	"\x14PlayerRespawnMessage\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"(\n" +
	"\fErrorMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xf9\x03\n" +
	"\vGameMessage\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.protocol.MessageTypeR\x04type\x12.\n" +
	"\x05input\x18\x03 \x01(\v2\x16.protocol.InputMessageH\x00R\x05input\x12;\n" +
	"\n" +
	"game_state\x18\x05 \x01(\v2\x1a.protocol.GameStateMessageH\x00R\tgameState\x12K\n" +
	"\x10game_state_delta\x18\v \x01(\v2\x1f.protocol.GameStateDeltaMessageH\x00R\x0egameStateDelta\x12>\n" +
	"\vplayer_join\x18\x06 \x01(\v2\x1b.protocol.PlayerJoinMessageH\x00R\n" +
	"playerJoin\x12A\n" +
	"\fplayer_leave\x18\a \x01(\v2\x1c.protocol.PlayerLeaveMessageH\x00R\vplayerLeave\x12G\n" +
	"\x0eplayer_respawn\x18\b \x01(\v2\x1e.protocol.PlayerRespawnMessageH\x00R\rplayerRespawn\x12.\n" +
	"\x05error\x18\n" +
	" \x01(\v2\x16.protocol.ErrorMessageH\x00R\x05errorB\t\n" +
	"\apayload*\x8d\x01\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05INPUT\x10\x02\x12\x0e\n" +
	"\n" +
	"GAME_STATE\x10\x05\x12\x14\n" +
	"\x10GAME_STATE_DELTA\x10\v\x12\x0f\n" +
	"\vPLAYER_JOIN\x10\x06\x12\x10\n" +
	"\fPLAYER_LEAVE\x10\a\x12\x12\n" +
	"\x0ePLAYER_RESPAWN\x10\b\x12\t\n" +
	"\x05ERROR\x10\n" +
	"B7Z5github.com/besuhoff/dungeon-game-go/internal/protocolb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_messages_proto_goTypes = []any{
	(MessageType)(0),              // 0: protocol.MessageType
	(*Vector2)(nil),               // 1: protocol.Vector2
	(*InventoryItem)(nil),         // 2: protocol.InventoryItem
	(*Player)(nil),                // 3: protocol.Player
	(*Bullet)(nil),                // 4: protocol.Bullet
	(*Wall)(nil),                  // 5: protocol.Wall
	(*Enemy)(nil),                 // 6: protocol.Enemy
	(*Bonus)(nil),                 // 7: protocol.Bonus
	(*Shop)(nil),                  // 8: protocol.Shop
	(*InputMessage)(nil),          // 9: protocol.InputMessage
	(*GameStateMessage)(nil),      // 10: protocol.GameStateMessage
	(*GameStateDeltaMessage)(nil), // 11: protocol.GameStateDeltaMessage
	(*PlayerJoinMessage)(nil),     // 12: protocol.PlayerJoinMessage
	(*PlayerLeaveMessage)(nil),    // 13: protocol.PlayerLeaveMessage
	(*PlayerRespawnMessage)(nil),  // 14: protocol.PlayerRespawnMessage
	(*ErrorMessage)(nil),          // 15: protocol.ErrorMessage
	(*GameMessage)(nil),           // 16: protocol.GameMessage
	nil,                           // 17: protocol.Player.BulletsLeftByWeaponTypeEntry
	nil,                           // 18: protocol.InputMessage.ItemKeyEntry
	nil,                           // 19: protocol.GameStateMessage.PlayersEntry
	nil,                           // 20: protocol.GameStateMessage.BulletsEntry
	nil,                           // 21: protocol.GameStateMessage.WallsEntry
	nil,                           // 22: protocol.GameStateMessage.EnemiesEntry
	nil,                           // 23: protocol.GameStateMessage.BonusesEntry
	nil,                           // 24: protocol.GameStateMessage.ShopsEntry
	nil,                           // 25: protocol.GameStateDeltaMessage.UpdatedPlayersEntry
	nil,                           // 26: protocol.GameStateDeltaMessage.UpdatedBulletsEntry
	nil,                           // 27: protocol.GameStateDeltaMessage.RemovedBulletsEntry
	nil,                           // 28: protocol.GameStateDeltaMessage.UpdatedWallsEntry
	nil,                           // 29: protocol.GameStateDeltaMessage.UpdatedEnemiesEntry
	nil,                           // 30: protocol.GameStateDeltaMessage.UpdatedBonusesEntry
	nil,                           // 31: protocol.GameStateDeltaMessage.UpdatedShopsEntry
}
var file_messages_proto_depIdxs = []int32{
	1,  // 0: protocol.Player.position:type_name -> protocol.Vector2
	1,  // 1: protocol.Player.velocity:type_name -> protocol.Vector2
	17, // 2: protocol.Player.bullets_left_by_weapon_type:type_name -> protocol.Player.BulletsLeftByWeaponTypeEntry
	2,  // 3: protocol.Player.inventory:type_name -> protocol.InventoryItem
	1,  // 4: protocol.Bullet.position:type_name -> protocol.Vector2
	1,  // 5: protocol.Bullet.velocity:type_name -> protocol.Vector2
	1,  // 6: protocol.Wall.position:type_name -> protocol.Vector2
	1,  // 7: protocol.Enemy.position:type_name -> protocol.Vector2
	1,  // 8: protocol.Bonus.position:type_name -> protocol.Vector2
	1,  // 9: protocol.Shop.position:type_name -> protocol.Vector2
	18, // 10: protocol.InputMessage.item_key:type_name -> protocol.InputMessage.ItemKeyEntry
	19, // 11: protocol.GameStateMessage.players:type_name -> protocol.GameStateMessage.PlayersEntry
	20, // 12: protocol.GameStateMessage.bullets:type_name -> protocol.GameStateMessage.BulletsEntry
	21, // 13: protocol.GameStateMessage.walls:type_name -> protocol.GameStateMessage.WallsEntry
	22, // 14: protocol.GameStateMessage.enemies:type_name -> protocol.GameStateMessage.EnemiesEntry
	23, // 15: protocol.GameStateMessage.bonuses:type_name -> protocol.GameStateMessage.BonusesEntry
	24, // 16: protocol.GameStateMessage.shops:type_name -> protocol.GameStateMessage.ShopsEntry
	25, // 17: protocol.GameStateDeltaMessage.updated_players:type_name -> protocol.GameStateDeltaMessage.UpdatedPlayersEntry
	26, // 18: protocol.GameStateDeltaMessage.updated_bullets:type_name -> protocol.GameStateDeltaMessage.UpdatedBulletsEntry
	27, // 19: protocol.GameStateDeltaMessage.removed_bullets:type_name -> protocol.GameStateDeltaMessage.RemovedBulletsEntry
	28, // 20: protocol.GameStateDeltaMessage.updated_walls:type_name -> protocol.GameStateDeltaMessage.UpdatedWallsEntry
	29, // 21: protocol.GameStateDeltaMessage.updated_enemies:type_name -> protocol.GameStateDeltaMessage.UpdatedEnemiesEntry
	30, // 22: protocol.GameStateDeltaMessage.updated_bonuses:type_name -> protocol.GameStateDeltaMessage.UpdatedBonusesEntry
	31, // 23: protocol.GameStateDeltaMessage.updated_shops:type_name -> protocol.GameStateDeltaMessage.UpdatedShopsEntry
	3,  // 24: protocol.PlayerJoinMessage.player:type_name -> protocol.Player
	0,  // 25: protocol.GameMessage.type:type_name -> protocol.MessageType
	9,  // 26: protocol.GameMessage.input:type_name -> protocol.InputMessage
	10, // 27: protocol.GameMessage.game_state:type_name -> protocol.GameStateMessage
	11, // 28: protocol.GameMessage.game_state_delta:type_name -> protocol.GameStateDeltaMessage
	12, // 29: protocol.GameMessage.player_join:type_name -> protocol.PlayerJoinMessage
	13, // 30: protocol.GameMessage.player_leave:type_name -> protocol.PlayerLeaveMessage
	14, // 31: protocol.GameMessage.player_respawn:type_name -> protocol.PlayerRespawnMessage
	15, // 32: protocol.GameMessage.error:type_name -> protocol.ErrorMessage
	3,  // 33: protocol.GameStateMessage.PlayersEntry.value:type_name -> protocol.Player
	4,  // 34: protocol.GameStateMessage.BulletsEntry.value:type_name -> protocol.Bullet
	5,  // 35: protocol.GameStateMessage.WallsEntry.value:type_name -> protocol.Wall
	6,  // 36: protocol.GameStateMessage.EnemiesEntry.value:type_name -> protocol.Enemy
	7,  // 37: protocol.GameStateMessage.BonusesEntry.value:type_name -> protocol.Bonus
	8,  // 38: protocol.GameStateMessage.ShopsEntry.value:type_name -> protocol.Shop
	3,  // 39: protocol.GameStateDeltaMessage.UpdatedPlayersEntry.value:type_name -> protocol.Player
	4,  // 40: protocol.GameStateDeltaMessage.UpdatedBulletsEntry.value:type_name -> protocol.Bullet
	4,  // 41: protocol.GameStateDeltaMessage.RemovedBulletsEntry.value:type_name -> protocol.Bullet
	5,  // 42: protocol.GameStateDeltaMessage.UpdatedWallsEntry.value:type_name -> protocol.Wall
	6,  // 43: protocol.GameStateDeltaMessage.UpdatedEnemiesEntry.value:type_name -> protocol.Enemy
	7,  // 44: protocol.GameStateDeltaMessage.UpdatedBonusesEntry.value:type_name -> protocol.Bonus
	8,  // 45: protocol.GameStateDeltaMessage.UpdatedShopsEntry.value:type_name -> protocol.Shop
	46, // [46:46] is the sub-list for method output_type
	46, // [46:46] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[15].OneofWrappers = []any{
		(*GameMessage_Input)(nil),
		(*GameMessage_GameState)(nil),
		(*GameMessage_GameStateDelta)(nil),
		(*GameMessage_PlayerJoin)(nil),
		(*GameMessage_PlayerLeave)(nil),
		(*GameMessage_PlayerRespawn)(nil),
		(*GameMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
