// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: messages.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message types
type MessageType int32

const (
	MessageType_UNKNOWN          MessageType = 0
	MessageType_INPUT            MessageType = 2
	MessageType_GAME_STATE       MessageType = 5
	MessageType_GAME_STATE_DELTA MessageType = 11
	MessageType_PLAYER_JOIN      MessageType = 6
	MessageType_PLAYER_LEAVE     MessageType = 7
	MessageType_PLAYER_RESPAWN   MessageType = 8
	MessageType_ERROR            MessageType = 10
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "UNKNOWN",
		2:  "INPUT",
		5:  "GAME_STATE",
		11: "GAME_STATE_DELTA",
		6:  "PLAYER_JOIN",
		7:  "PLAYER_LEAVE",
		8:  "PLAYER_RESPAWN",
		10: "ERROR",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":          0,
		"INPUT":            2,
		"GAME_STATE":       5,
		"GAME_STATE_DELTA": 11,
		"PLAYER_JOIN":      6,
		"PLAYER_LEAVE":     7,
		"PLAYER_RESPAWN":   8,
		"ERROR":            10,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

// Common structures
type Vector2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector2) Reset() {
	*x = Vector2{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2) ProtoMessage() {}

func (x *Vector2) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2.ProtoReflect.Descriptor instead.
func (*Vector2) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Vector2) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector2) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type InventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *InventoryItem) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *InventoryItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Player struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username                string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Position                *Vector2               `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Velocity                *Vector2               `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Lives                   float32                `protobuf:"fixed32,5,opt,name=lives,proto3" json:"lives,omitempty"`
	InvulnerableTimer       float64                `protobuf:"fixed64,13,opt,name=invulnerable_timer,json=invulnerableTimer,proto3" json:"invulnerable_timer,omitempty"`
	Score                   int32                  `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	Money                   int32                  `protobuf:"varint,7,opt,name=money,proto3" json:"money,omitempty"`
	Kills                   int32                  `protobuf:"varint,8,opt,name=kills,proto3" json:"kills,omitempty"`
	Rotation                float64                `protobuf:"fixed64,9,opt,name=rotation,proto3" json:"rotation,omitempty"`
	BulletsLeftByWeaponType map[string]int32       `protobuf:"bytes,10,rep,name=bullets_left_by_weapon_type,json=bulletsLeftByWeaponType,proto3" json:"bullets_left_by_weapon_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	NightVisionTimer        float64                `protobuf:"fixed64,11,opt,name=night_vision_timer,json=nightVisionTimer,proto3" json:"night_vision_timer,omitempty"`
	IsAlive                 bool                   `protobuf:"varint,12,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	Inventory               []*InventoryItem       `protobuf:"bytes,14,rep,name=inventory,proto3" json:"inventory,omitempty"`
	SelectedGunType         string                 `protobuf:"bytes,15,opt,name=selected_gun_type,json=selectedGunType,proto3" json:"selected_gun_type,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Player) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Player) GetVelocity() *Vector2 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *Player) GetLives() float32 {
	if x != nil {
		return x.Lives
	}
	return 0
}

func (x *Player) GetInvulnerableTimer() float64 {
	if x != nil {
		return x.InvulnerableTimer
	}
	return 0
}

func (x *Player) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Player) GetMoney() int32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *Player) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *Player) GetRotation() float64 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *Player) GetBulletsLeftByWeaponType() map[string]int32 {
	if x != nil {
		return x.BulletsLeftByWeaponType
	}
	return nil
}

func (x *Player) GetNightVisionTimer() float64 {
	if x != nil {
		return x.NightVisionTimer
	}
	return 0
}

func (x *Player) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

func (x *Player) GetInventory() []*InventoryItem {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *Player) GetSelectedGunType() string {
	if x != nil {
		return x.SelectedGunType
	}
	return ""
}

type Bullet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vector2               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Velocity      *Vector2               `protobuf:"bytes,3,opt,name=velocity,proto3" json:"velocity,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Damage        float32                `protobuf:"fixed32,5,opt,name=damage,proto3" json:"damage,omitempty"`
	IsEnemy       bool                   `protobuf:"varint,6,opt,name=is_enemy,json=isEnemy,proto3" json:"is_enemy,omitempty"`
	EnemyType     string                 `protobuf:"bytes,11,opt,name=enemy_type,json=enemyType,proto3" json:"enemy_type,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	DeletedAt     int64                  `protobuf:"varint,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	InactiveMs    int64                  `protobuf:"varint,9,opt,name=inactive_ms,json=inactiveMs,proto3" json:"inactive_ms,omitempty"`
	WeaponType    string                 `protobuf:"bytes,8,opt,name=weapon_type,json=weaponType,proto3" json:"weapon_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bullet) Reset() {
	*x = Bullet{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bullet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bullet) ProtoMessage() {}

func (x *Bullet) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bullet.ProtoReflect.Descriptor instead.
func (*Bullet) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Bullet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bullet) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Bullet) GetVelocity() *Vector2 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *Bullet) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Bullet) GetDamage() float32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *Bullet) GetIsEnemy() bool {
	if x != nil {
		return x.IsEnemy
	}
	return false
}

func (x *Bullet) GetEnemyType() string {
	if x != nil {
		return x.EnemyType
	}
	return ""
}

func (x *Bullet) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Bullet) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *Bullet) GetInactiveMs() int64 {
	if x != nil {
		return x.InactiveMs
	}
	return 0
}

func (x *Bullet) GetWeaponType() string {
	if x != nil {
		return x.WeaponType
	}
	return ""
}

type Wall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vector2               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Width         float64                `protobuf:"fixed64,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,4,opt,name=height,proto3" json:"height,omitempty"`
	Orientation   string                 `protobuf:"bytes,5,opt,name=orientation,proto3" json:"orientation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wall) Reset() {
	*x = Wall{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wall) ProtoMessage() {}

func (x *Wall) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wall.ProtoReflect.Descriptor instead.
func (*Wall) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Wall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wall) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Wall) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Wall) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Wall) GetOrientation() string {
	if x != nil {
		return x.Orientation
	}
	return ""
}

type Enemy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vector2               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation      float64                `protobuf:"fixed64,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Lives         float32                `protobuf:"fixed32,4,opt,name=lives,proto3" json:"lives,omitempty"`
	WallId        string                 `protobuf:"bytes,5,opt,name=wall_id,json=wallId,proto3" json:"wall_id,omitempty"`
	IsAlive       bool                   `protobuf:"varint,6,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enemy) Reset() {
	*x = Enemy{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enemy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enemy) ProtoMessage() {}

func (x *Enemy) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enemy.ProtoReflect.Descriptor instead.
func (*Enemy) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Enemy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Enemy) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Enemy) GetRotation() float64 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *Enemy) GetLives() float32 {
	if x != nil {
		return x.Lives
	}
	return 0
}

func (x *Enemy) GetWallId() string {
	if x != nil {
		return x.WallId
	}
	return ""
}

func (x *Enemy) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

func (x *Enemy) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Bonus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vector2               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	PickedUpBy    string                 `protobuf:"bytes,4,opt,name=picked_up_by,json=pickedUpBy,proto3" json:"picked_up_by,omitempty"`
	DroppedBy     string                 `protobuf:"bytes,5,opt,name=dropped_by,json=droppedBy,proto3" json:"dropped_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bonus) Reset() {
	*x = Bonus{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bonus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bonus) ProtoMessage() {}

func (x *Bonus) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bonus.ProtoReflect.Descriptor instead.
func (*Bonus) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *Bonus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bonus) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Bonus) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Bonus) GetPickedUpBy() string {
	if x != nil {
		return x.PickedUpBy
	}
	return ""
}

func (x *Bonus) GetDroppedBy() string {
	if x != nil {
		return x.DroppedBy
	}
	return ""
}

type ShopItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantity      int32                  `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PackSize      int32                  `protobuf:"varint,2,opt,name=pack_size,json=packSize,proto3" json:"pack_size,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopItem) Reset() {
	*x = ShopItem{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopItem) ProtoMessage() {}

func (x *ShopItem) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopItem.ProtoReflect.Descriptor instead.
func (*ShopItem) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ShopItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ShopItem) GetPackSize() int32 {
	if x != nil {
		return x.PackSize
	}
	return 0
}

func (x *ShopItem) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Shop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vector2               `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Inventory     map[int32]*ShopItem    `protobuf:"bytes,3,rep,name=inventory,proto3" json:"inventory,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shop) Reset() {
	*x = Shop{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shop) ProtoMessage() {}

func (x *Shop) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shop.ProtoReflect.Descriptor instead.
func (*Shop) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *Shop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shop) GetPosition() *Vector2 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Shop) GetInventory() map[int32]*ShopItem {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *Shop) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InputMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Forward         bool                   `protobuf:"varint,1,opt,name=forward,proto3" json:"forward,omitempty"`
	Backward        bool                   `protobuf:"varint,2,opt,name=backward,proto3" json:"backward,omitempty"`
	Left            bool                   `protobuf:"varint,3,opt,name=left,proto3" json:"left,omitempty"`
	Right           bool                   `protobuf:"varint,4,opt,name=right,proto3" json:"right,omitempty"`
	Shoot           bool                   `protobuf:"varint,5,opt,name=shoot,proto3" json:"shoot,omitempty"`
	ItemKey         map[int32]bool         `protobuf:"bytes,6,rep,name=item_key,json=itemKey,proto3" json:"item_key,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	PurchaseItemKey map[int32]bool         `protobuf:"bytes,7,rep,name=purchase_item_key,json=purchaseItemKey,proto3" json:"purchase_item_key,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InputMessage) Reset() {
	*x = InputMessage{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputMessage) ProtoMessage() {}

func (x *InputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputMessage.ProtoReflect.Descriptor instead.
func (*InputMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *InputMessage) GetForward() bool {
	if x != nil {
		return x.Forward
	}
	return false
}

func (x *InputMessage) GetBackward() bool {
	if x != nil {
		return x.Backward
	}
	return false
}

func (x *InputMessage) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

func (x *InputMessage) GetRight() bool {
	if x != nil {
		return x.Right
	}
	return false
}

func (x *InputMessage) GetShoot() bool {
	if x != nil {
		return x.Shoot
	}
	return false
}

func (x *InputMessage) GetItemKey() map[int32]bool {
	if x != nil {
		return x.ItemKey
	}
	return nil
}

func (x *InputMessage) GetPurchaseItemKey() map[int32]bool {
	if x != nil {
		return x.PurchaseItemKey
	}
	return nil
}

type PositionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Rotation      float64                `protobuf:"fixed64,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionUpdate) Reset() {
	*x = PositionUpdate{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionUpdate) ProtoMessage() {}

func (x *PositionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionUpdate.ProtoReflect.Descriptor instead.
func (*PositionUpdate) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *PositionUpdate) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PositionUpdate) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PositionUpdate) GetRotation() float64 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

type TimersUpdate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InvulnerableTimer float64                `protobuf:"fixed64,1,opt,name=invulnerable_timer,json=invulnerableTimer,proto3" json:"invulnerable_timer,omitempty"`
	NightVisionTimer  float64                `protobuf:"fixed64,2,opt,name=night_vision_timer,json=nightVisionTimer,proto3" json:"night_vision_timer,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TimersUpdate) Reset() {
	*x = TimersUpdate{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimersUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimersUpdate) ProtoMessage() {}

func (x *TimersUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimersUpdate.ProtoReflect.Descriptor instead.
func (*TimersUpdate) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *TimersUpdate) GetInvulnerableTimer() float64 {
	if x != nil {
		return x.InvulnerableTimer
	}
	return 0
}

func (x *TimersUpdate) GetNightVisionTimer() float64 {
	if x != nil {
		return x.NightVisionTimer
	}
	return 0
}

type LivesUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lives         float32                `protobuf:"fixed32,1,opt,name=lives,proto3" json:"lives,omitempty"`
	IsAlive       bool                   `protobuf:"varint,2,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivesUpdate) Reset() {
	*x = LivesUpdate{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivesUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivesUpdate) ProtoMessage() {}

func (x *LivesUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivesUpdate.ProtoReflect.Descriptor instead.
func (*LivesUpdate) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *LivesUpdate) GetLives() float32 {
	if x != nil {
		return x.Lives
	}
	return 0
}

func (x *LivesUpdate) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

type InventoryUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Inventory       []*InventoryItem       `protobuf:"bytes,1,rep,name=inventory,proto3" json:"inventory,omitempty"`
	SelectedGunType string                 `protobuf:"bytes,2,opt,name=selected_gun_type,json=selectedGunType,proto3" json:"selected_gun_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InventoryUpdate) Reset() {
	*x = InventoryUpdate{}
	mi := &file_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryUpdate) ProtoMessage() {}

func (x *InventoryUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryUpdate.ProtoReflect.Descriptor instead.
func (*InventoryUpdate) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *InventoryUpdate) GetInventory() []*InventoryItem {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *InventoryUpdate) GetSelectedGunType() string {
	if x != nil {
		return x.SelectedGunType
	}
	return ""
}

type ScoreUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int32                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Money         int32                  `protobuf:"varint,2,opt,name=money,proto3" json:"money,omitempty"`
	Kills         int32                  `protobuf:"varint,3,opt,name=kills,proto3" json:"kills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreUpdate) Reset() {
	*x = ScoreUpdate{}
	mi := &file_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreUpdate) ProtoMessage() {}

func (x *ScoreUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreUpdate.ProtoReflect.Descriptor instead.
func (*ScoreUpdate) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *ScoreUpdate) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoreUpdate) GetMoney() int32 {
	if x != nil {
		return x.Money
	}
	return 0
}

func (x *ScoreUpdate) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

type PlayerBulletsUpdate struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	BulletsLeftByWeaponType map[string]int32       `protobuf:"bytes,1,rep,name=bullets_left_by_weapon_type,json=bulletsLeftByWeaponType,proto3" json:"bullets_left_by_weapon_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PlayerBulletsUpdate) Reset() {
	*x = PlayerBulletsUpdate{}
	mi := &file_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBulletsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBulletsUpdate) ProtoMessage() {}

func (x *PlayerBulletsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBulletsUpdate.ProtoReflect.Descriptor instead.
func (*PlayerBulletsUpdate) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

func (x *PlayerBulletsUpdate) GetBulletsLeftByWeaponType() map[string]int32 {
	if x != nil {
		return x.BulletsLeftByWeaponType
	}
	return nil
}

type PlayerUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *PositionUpdate        `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Timers        *TimersUpdate          `protobuf:"bytes,2,opt,name=timers,proto3" json:"timers,omitempty"`
	Lives         *LivesUpdate           `protobuf:"bytes,3,opt,name=lives,proto3" json:"lives,omitempty"`
	Inventory     *InventoryUpdate       `protobuf:"bytes,4,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Score         *ScoreUpdate           `protobuf:"bytes,5,opt,name=score,proto3" json:"score,omitempty"`
	PlayerBullets *PlayerBulletsUpdate   `protobuf:"bytes,6,opt,name=player_bullets,json=playerBullets,proto3" json:"player_bullets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerUpdate) Reset() {
	*x = PlayerUpdate{}
	mi := &file_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerUpdate) ProtoMessage() {}

func (x *PlayerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerUpdate.ProtoReflect.Descriptor instead.
func (*PlayerUpdate) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{16}
}

func (x *PlayerUpdate) GetPosition() *PositionUpdate {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PlayerUpdate) GetTimers() *TimersUpdate {
	if x != nil {
		return x.Timers
	}
	return nil
}

func (x *PlayerUpdate) GetLives() *LivesUpdate {
	if x != nil {
		return x.Lives
	}
	return nil
}

func (x *PlayerUpdate) GetInventory() *InventoryUpdate {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *PlayerUpdate) GetScore() *ScoreUpdate {
	if x != nil {
		return x.Score
	}
	return nil
}

func (x *PlayerUpdate) GetPlayerBullets() *PlayerBulletsUpdate {
	if x != nil {
		return x.PlayerBullets
	}
	return nil
}

type DeletionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	DeletedAt     int64                  `protobuf:"varint,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletionUpdate) Reset() {
	*x = DeletionUpdate{}
	mi := &file_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletionUpdate) ProtoMessage() {}

func (x *DeletionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletionUpdate.ProtoReflect.Descriptor instead.
func (*DeletionUpdate) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{17}
}

func (x *DeletionUpdate) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *DeletionUpdate) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

type EnemyUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *PositionUpdate        `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Lives         *LivesUpdate           `protobuf:"bytes,2,opt,name=lives,proto3" json:"lives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnemyUpdate) Reset() {
	*x = EnemyUpdate{}
	mi := &file_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnemyUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnemyUpdate) ProtoMessage() {}

func (x *EnemyUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnemyUpdate.ProtoReflect.Descriptor instead.
func (*EnemyUpdate) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{18}
}

func (x *EnemyUpdate) GetPosition() *PositionUpdate {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EnemyUpdate) GetLives() *LivesUpdate {
	if x != nil {
		return x.Lives
	}
	return nil
}

type BonusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PickedUpBy    string                 `protobuf:"bytes,1,opt,name=picked_up_by,json=pickedUpBy,proto3" json:"picked_up_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BonusUpdate) Reset() {
	*x = BonusUpdate{}
	mi := &file_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BonusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BonusUpdate) ProtoMessage() {}

func (x *BonusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BonusUpdate.ProtoReflect.Descriptor instead.
func (*BonusUpdate) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{19}
}

func (x *BonusUpdate) GetPickedUpBy() string {
	if x != nil {
		return x.PickedUpBy
	}
	return ""
}

type ShopUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inventory     map[int32]*ShopItem    `protobuf:"bytes,1,rep,name=inventory,proto3" json:"inventory,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopUpdate) Reset() {
	*x = ShopUpdate{}
	mi := &file_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopUpdate) ProtoMessage() {}

func (x *ShopUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopUpdate.ProtoReflect.Descriptor instead.
func (*ShopUpdate) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{20}
}

func (x *ShopUpdate) GetInventory() map[int32]*ShopItem {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type GameStateDeltaMessage struct {
	state                       protoimpl.MessageState     `protogen:"open.v1"`
	AddedPlayers                map[string]*Player         `protobuf:"bytes,1,rep,name=added_players,json=addedPlayers,proto3" json:"added_players,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedPlayers              map[string]*PlayerUpdate   `protobuf:"bytes,2,rep,name=updated_players,json=updatedPlayers,proto3" json:"updated_players,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemovedPlayers              []string                   `protobuf:"bytes,3,rep,name=removed_players,json=removedPlayers,proto3" json:"removed_players,omitempty"`
	AddedBullets                map[string]*Bullet         `protobuf:"bytes,4,rep,name=added_bullets,json=addedBullets,proto3" json:"added_bullets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedBullets              map[string]*PositionUpdate `protobuf:"bytes,5,rep,name=updated_bullets,json=updatedBullets,proto3" json:"updated_bullets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemovedBullets              map[string]*Bullet         `protobuf:"bytes,6,rep,name=removed_bullets,json=removedBullets,proto3" json:"removed_bullets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AddedWalls                  map[string]*Wall           `protobuf:"bytes,7,rep,name=added_walls,json=addedWalls,proto3" json:"added_walls,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemovedWalls                []string                   `protobuf:"bytes,8,rep,name=removed_walls,json=removedWalls,proto3" json:"removed_walls,omitempty"`
	AddedEnemies                map[string]*Enemy          `protobuf:"bytes,9,rep,name=added_enemies,json=addedEnemies,proto3" json:"added_enemies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedEnemies              map[string]*EnemyUpdate    `protobuf:"bytes,10,rep,name=updated_enemies,json=updatedEnemies,proto3" json:"updated_enemies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemovedEnemies              []string                   `protobuf:"bytes,11,rep,name=removed_enemies,json=removedEnemies,proto3" json:"removed_enemies,omitempty"`
	AddedBonuses                map[string]*Bonus          `protobuf:"bytes,12,rep,name=added_bonuses,json=addedBonuses,proto3" json:"added_bonuses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedBonuses              map[string]*BonusUpdate    `protobuf:"bytes,13,rep,name=updated_bonuses,json=updatedBonuses,proto3" json:"updated_bonuses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemovedBonuses              []string                   `protobuf:"bytes,14,rep,name=removed_bonuses,json=removedBonuses,proto3" json:"removed_bonuses,omitempty"`
	AddedShops                  map[string]*Shop           `protobuf:"bytes,15,rep,name=added_shops,json=addedShops,proto3" json:"added_shops,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedShops                map[string]*ShopUpdate     `protobuf:"bytes,16,rep,name=updated_shops,json=updatedShops,proto3" json:"updated_shops,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemovedShops                []string                   `protobuf:"bytes,17,rep,name=removed_shops,json=removedShops,proto3" json:"removed_shops,omitempty"`
	AddedPlayersShops           []string                   `protobuf:"bytes,18,rep,name=added_players_shops,json=addedPlayersShops,proto3" json:"added_players_shops,omitempty"`
	RemovedPlayersShops         []string                   `protobuf:"bytes,19,rep,name=removed_players_shops,json=removedPlayersShops,proto3" json:"removed_players_shops,omitempty"`
	UpdatedOtherPlayerPositions map[string]*Vector2        `protobuf:"bytes,20,rep,name=updated_other_player_positions,json=updatedOtherPlayerPositions,proto3" json:"updated_other_player_positions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RemovedOtherPlayerPositions []string                   `protobuf:"bytes,21,rep,name=removed_other_player_positions,json=removedOtherPlayerPositions,proto3" json:"removed_other_player_positions,omitempty"`
	Timestamp                   int64                      `protobuf:"varint,22,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *GameStateDeltaMessage) Reset() {
	*x = GameStateDeltaMessage{}
	mi := &file_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateDeltaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateDeltaMessage) ProtoMessage() {}

func (x *GameStateDeltaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateDeltaMessage.ProtoReflect.Descriptor instead.
func (*GameStateDeltaMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{21}
}

func (x *GameStateDeltaMessage) GetAddedPlayers() map[string]*Player {
	if x != nil {
		return x.AddedPlayers
	}
	return nil
}

func (x *GameStateDeltaMessage) GetUpdatedPlayers() map[string]*PlayerUpdate {
	if x != nil {
		return x.UpdatedPlayers
	}
	return nil
}

func (x *GameStateDeltaMessage) GetRemovedPlayers() []string {
	if x != nil {
		return x.RemovedPlayers
	}
	return nil
}

func (x *GameStateDeltaMessage) GetAddedBullets() map[string]*Bullet {
	if x != nil {
		return x.AddedBullets
	}
	return nil
}

func (x *GameStateDeltaMessage) GetUpdatedBullets() map[string]*PositionUpdate {
	if x != nil {
		return x.UpdatedBullets
	}
	return nil
}

func (x *GameStateDeltaMessage) GetRemovedBullets() map[string]*Bullet {
	if x != nil {
		return x.RemovedBullets
	}
	return nil
}

func (x *GameStateDeltaMessage) GetAddedWalls() map[string]*Wall {
	if x != nil {
		return x.AddedWalls
	}
	return nil
}

func (x *GameStateDeltaMessage) GetRemovedWalls() []string {
	if x != nil {
		return x.RemovedWalls
	}
	return nil
}

func (x *GameStateDeltaMessage) GetAddedEnemies() map[string]*Enemy {
	if x != nil {
		return x.AddedEnemies
	}
	return nil
}

func (x *GameStateDeltaMessage) GetUpdatedEnemies() map[string]*EnemyUpdate {
	if x != nil {
		return x.UpdatedEnemies
	}
	return nil
}

func (x *GameStateDeltaMessage) GetRemovedEnemies() []string {
	if x != nil {
		return x.RemovedEnemies
	}
	return nil
}

func (x *GameStateDeltaMessage) GetAddedBonuses() map[string]*Bonus {
	if x != nil {
		return x.AddedBonuses
	}
	return nil
}

func (x *GameStateDeltaMessage) GetUpdatedBonuses() map[string]*BonusUpdate {
	if x != nil {
		return x.UpdatedBonuses
	}
	return nil
}

func (x *GameStateDeltaMessage) GetRemovedBonuses() []string {
	if x != nil {
		return x.RemovedBonuses
	}
	return nil
}

func (x *GameStateDeltaMessage) GetAddedShops() map[string]*Shop {
	if x != nil {
		return x.AddedShops
	}
	return nil
}

func (x *GameStateDeltaMessage) GetUpdatedShops() map[string]*ShopUpdate {
	if x != nil {
		return x.UpdatedShops
	}
	return nil
}

func (x *GameStateDeltaMessage) GetRemovedShops() []string {
	if x != nil {
		return x.RemovedShops
	}
	return nil
}

func (x *GameStateDeltaMessage) GetAddedPlayersShops() []string {
	if x != nil {
		return x.AddedPlayersShops
	}
	return nil
}

func (x *GameStateDeltaMessage) GetRemovedPlayersShops() []string {
	if x != nil {
		return x.RemovedPlayersShops
	}
	return nil
}

func (x *GameStateDeltaMessage) GetUpdatedOtherPlayerPositions() map[string]*Vector2 {
	if x != nil {
		return x.UpdatedOtherPlayerPositions
	}
	return nil
}

func (x *GameStateDeltaMessage) GetRemovedOtherPlayerPositions() []string {
	if x != nil {
		return x.RemovedOtherPlayerPositions
	}
	return nil
}

func (x *GameStateDeltaMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PlayerJoinMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoinMessage) Reset() {
	*x = PlayerJoinMessage{}
	mi := &file_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoinMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoinMessage) ProtoMessage() {}

func (x *PlayerJoinMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoinMessage.ProtoReflect.Descriptor instead.
func (*PlayerJoinMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{22}
}

func (x *PlayerJoinMessage) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type PlayerLeaveMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeaveMessage) Reset() {
	*x = PlayerLeaveMessage{}
	mi := &file_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeaveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeaveMessage) ProtoMessage() {}

func (x *PlayerLeaveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeaveMessage.ProtoReflect.Descriptor instead.
func (*PlayerLeaveMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{23}
}

func (x *PlayerLeaveMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type PlayerRespawnMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRespawnMessage) Reset() {
	*x = PlayerRespawnMessage{}
	mi := &file_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRespawnMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRespawnMessage) ProtoMessage() {}

func (x *PlayerRespawnMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRespawnMessage.ProtoReflect.Descriptor instead.
func (*PlayerRespawnMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{24}
}

type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{25}
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Wrapper message
type GameMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GameMessage_Input
	//	*GameMessage_GameStateDelta
	//	*GameMessage_PlayerJoin
	//	*GameMessage_PlayerLeave
	//	*GameMessage_PlayerRespawn
	//	*GameMessage_Error
	Payload       isGameMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_messages_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{26}
}

func (x *GameMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *GameMessage) GetPayload() isGameMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameMessage) GetInput() *InputMessage {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *GameMessage) GetGameStateDelta() *GameStateDeltaMessage {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_GameStateDelta); ok {
			return x.GameStateDelta
		}
	}
	return nil
}

func (x *GameMessage) GetPlayerJoin() *PlayerJoinMessage {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_PlayerJoin); ok {
			return x.PlayerJoin
		}
	}
	return nil
}

func (x *GameMessage) GetPlayerLeave() *PlayerLeaveMessage {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_PlayerLeave); ok {
			return x.PlayerLeave
		}
	}
	return nil
}

func (x *GameMessage) GetPlayerRespawn() *PlayerRespawnMessage {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_PlayerRespawn); ok {
			return x.PlayerRespawn
		}
	}
	return nil
}

func (x *GameMessage) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Payload.(*GameMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGameMessage_Payload interface {
	isGameMessage_Payload()
}

type GameMessage_Input struct {
	Input *InputMessage `protobuf:"bytes,3,opt,name=input,proto3,oneof"`
}

type GameMessage_GameStateDelta struct {
	GameStateDelta *GameStateDeltaMessage `protobuf:"bytes,11,opt,name=game_state_delta,json=gameStateDelta,proto3,oneof"`
}

type GameMessage_PlayerJoin struct {
	PlayerJoin *PlayerJoinMessage `protobuf:"bytes,6,opt,name=player_join,json=playerJoin,proto3,oneof"`
}

type GameMessage_PlayerLeave struct {
	PlayerLeave *PlayerLeaveMessage `protobuf:"bytes,7,opt,name=player_leave,json=playerLeave,proto3,oneof"`
}

type GameMessage_PlayerRespawn struct {
	PlayerRespawn *PlayerRespawnMessage `protobuf:"bytes,8,opt,name=player_respawn,json=playerRespawn,proto3,oneof"`
}

type GameMessage_Error struct {
	Error *ErrorMessage `protobuf:"bytes,10,opt,name=error,proto3,oneof"`
}

func (*GameMessage_Input) isGameMessage_Payload() {}

func (*GameMessage_GameStateDelta) isGameMessage_Payload() {}

func (*GameMessage_PlayerJoin) isGameMessage_Payload() {}

func (*GameMessage_PlayerLeave) isGameMessage_Payload() {}

func (*GameMessage_PlayerRespawn) isGameMessage_Payload() {}

func (*GameMessage_Error) isGameMessage_Payload() {}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\bprotocol\"%\n" +
	"\aVector2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"?\n" +
	"\rInventoryItem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\x9a\x05\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12-\n" +
	"\bposition\x18\x03 \x01(\v2\x11.protocol.Vector2R\bposition\x12-\n" +
	"\bvelocity\x18\x04 \x01(\v2\x11.protocol.Vector2R\bvelocity\x12\x14\n" +
	"\x05lives\x18\x05 \x01(\x02R\x05lives\x12-\n" +
	"\x12invulnerable_timer\x18\r \x01(\x01R\x11invulnerableTimer\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x05R\x05score\x12\x14\n" +
	"\x05money\x18\a \x01(\x05R\x05money\x12\x14\n" +
	"\x05kills\x18\b \x01(\x05R\x05kills\x12\x1a\n" +
	"\brotation\x18\t \x01(\x01R\brotation\x12k\n" +
	"\x1bbullets_left_by_weapon_type\x18\n" +
	" \x03(\v2-.protocol.Player.BulletsLeftByWeaponTypeEntryR\x17bulletsLeftByWeaponType\x12,\n" +
	"\x12night_vision_timer\x18\v \x01(\x01R\x10nightVisionTimer\x12\x19\n" +
	"\bis_alive\x18\f \x01(\bR\aisAlive\x125\n" +
	"\tinventory\x18\x0e \x03(\v2\x17.protocol.InventoryItemR\tinventory\x12*\n" +
	"\x11selected_gun_type\x18\x0f \x01(\tR\x0fselectedGunType\x1aJ\n" +
	"\x1cBulletsLeftByWeaponTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xe1\x02\n" +
	"\x06Bullet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.protocol.Vector2R\bposition\x12-\n" +
	"\bvelocity\x18\x03 \x01(\v2\x11.protocol.Vector2R\bvelocity\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12\x16\n" +
	"\x06damage\x18\x05 \x01(\x02R\x06damage\x12\x19\n" +
	"\bis_enemy\x18\x06 \x01(\bR\aisEnemy\x12\x1d\n" +
	"\n" +
	"enemy_type\x18\v \x01(\tR\tenemyType\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\x03R\tdeletedAt\x12\x1f\n" +
	"\vinactive_ms\x18\t \x01(\x03R\n" +
	"inactiveMs\x12\x1f\n" +
	"\vweapon_type\x18\b \x01(\tR\n" +
	"weaponType\"\x95\x01\n" +
	"\x04Wall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.protocol.Vector2R\bposition\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x01R\x06height\x12 \n" +
	"\vorientation\x18\x05 \x01(\tR\vorientation\"\xc0\x01\n" +
	"\x05Enemy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.protocol.Vector2R\bposition\x12\x1a\n" +
	"\brotation\x18\x03 \x01(\x01R\brotation\x12\x14\n" +
	"\x05lives\x18\x04 \x01(\x02R\x05lives\x12\x17\n" +
	"\awall_id\x18\x05 \x01(\tR\x06wallId\x12\x19\n" +
	"\bis_alive\x18\x06 \x01(\bR\aisAlive\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\"\x9b\x01\n" +
	"\x05Bonus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.protocol.Vector2R\bposition\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\fpicked_up_by\x18\x04 \x01(\tR\n" +
	"pickedUpBy\x12\x1d\n" +
	"\n" +
	"dropped_by\x18\x05 \x01(\tR\tdroppedBy\"Y\n" +
	"\bShopItem\x12\x1a\n" +
	"\bquantity\x18\x01 \x01(\x05R\bquantity\x12\x1b\n" +
	"\tpack_size\x18\x02 \x01(\x05R\bpackSize\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\"\xe8\x01\n" +
	"\x04Shop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.protocol.Vector2R\bposition\x12;\n" +
	"\tinventory\x18\x03 \x03(\v2\x1d.protocol.Shop.InventoryEntryR\tinventory\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x1aP\n" +
	"\x0eInventoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.protocol.ShopItemR\x05value:\x028\x01\"\x9d\x03\n" +
	"\fInputMessage\x12\x18\n" +
	"\aforward\x18\x01 \x01(\bR\aforward\x12\x1a\n" +
	"\bbackward\x18\x02 \x01(\bR\bbackward\x12\x12\n" +
	"\x04left\x18\x03 \x01(\bR\x04left\x12\x14\n" +
	"\x05right\x18\x04 \x01(\bR\x05right\x12\x14\n" +
	"\x05shoot\x18\x05 \x01(\bR\x05shoot\x12>\n" +
	"\bitem_key\x18\x06 \x03(\v2#.protocol.InputMessage.ItemKeyEntryR\aitemKey\x12W\n" +
	"\x11purchase_item_key\x18\a \x03(\v2+.protocol.InputMessage.PurchaseItemKeyEntryR\x0fpurchaseItemKey\x1a:\n" +
	"\fItemKeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1aB\n" +
	"\x14PurchaseItemKeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"H\n" +
	"\x0ePositionUpdate\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12\x1a\n" +
	"\brotation\x18\x03 \x01(\x01R\brotation\"k\n" +
	"\fTimersUpdate\x12-\n" +
	"\x12invulnerable_timer\x18\x01 \x01(\x01R\x11invulnerableTimer\x12,\n" +
	"\x12night_vision_timer\x18\x02 \x01(\x01R\x10nightVisionTimer\">\n" +
	"\vLivesUpdate\x12\x14\n" +
	"\x05lives\x18\x01 \x01(\x02R\x05lives\x12\x19\n" +
	"\bis_alive\x18\x02 \x01(\bR\aisAlive\"t\n" +
	"\x0fInventoryUpdate\x125\n" +
	"\tinventory\x18\x01 \x03(\v2\x17.protocol.InventoryItemR\tinventory\x12*\n" +
	"\x11selected_gun_type\x18\x02 \x01(\tR\x0fselectedGunType\"O\n" +
	"\vScoreUpdate\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x05R\x05score\x12\x14\n" +
	"\x05money\x18\x02 \x01(\x05R\x05money\x12\x14\n" +
	"\x05kills\x18\x03 \x01(\x05R\x05kills\"\xdb\x01\n" +
	"\x13PlayerBulletsUpdate\x12x\n" +
	"\x1bbullets_left_by_weapon_type\x18\x01 \x03(\v2:.protocol.PlayerBulletsUpdate.BulletsLeftByWeaponTypeEntryR\x17bulletsLeftByWeaponType\x1aJ\n" +
	"\x1cBulletsLeftByWeaponTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xcd\x02\n" +
	"\fPlayerUpdate\x124\n" +
	"\bposition\x18\x01 \x01(\v2\x18.protocol.PositionUpdateR\bposition\x12.\n" +
	"\x06timers\x18\x02 \x01(\v2\x16.protocol.TimersUpdateR\x06timers\x12+\n" +
	"\x05lives\x18\x03 \x01(\v2\x15.protocol.LivesUpdateR\x05lives\x127\n" +
	"\tinventory\x18\x04 \x01(\v2\x19.protocol.InventoryUpdateR\tinventory\x12+\n" +
	"\x05score\x18\x05 \x01(\v2\x15.protocol.ScoreUpdateR\x05score\x12D\n" +
	"\x0eplayer_bullets\x18\x06 \x01(\v2\x1d.protocol.PlayerBulletsUpdateR\rplayerBullets\"L\n" +
	"\x0eDeletionUpdate\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\x03R\tdeletedAt\"p\n" +
	"\vEnemyUpdate\x124\n" +
	"\bposition\x18\x01 \x01(\v2\x18.protocol.PositionUpdateR\bposition\x12+\n" +
	"\x05lives\x18\x02 \x01(\v2\x15.protocol.LivesUpdateR\x05lives\"/\n" +
	"\vBonusUpdate\x12 \n" +
	"\fpicked_up_by\x18\x01 \x01(\tR\n" +
	"pickedUpBy\"\xa1\x01\n" +
	"\n" +
	"ShopUpdate\x12A\n" +
	"\tinventory\x18\x01 \x03(\v2#.protocol.ShopUpdate.InventoryEntryR\tinventory\x1aP\n" +
	"\x0eInventoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.protocol.ShopItemR\x05value:\x028\x01\"\xc0\x15\n" +
	"\x15GameStateDeltaMessage\x12V\n" +
	"\radded_players\x18\x01 \x03(\v21.protocol.GameStateDeltaMessage.AddedPlayersEntryR\faddedPlayers\x12\\\n" +
	"\x0fupdated_players\x18\x02 \x03(\v23.protocol.GameStateDeltaMessage.UpdatedPlayersEntryR\x0eupdatedPlayers\x12'\n" +
	"\x0fremoved_players\x18\x03 \x03(\tR\x0eremovedPlayers\x12V\n" +
	"\radded_bullets\x18\x04 \x03(\v21.protocol.GameStateDeltaMessage.AddedBulletsEntryR\faddedBullets\x12\\\n" +
	"\x0fupdated_bullets\x18\x05 \x03(\v23.protocol.GameStateDeltaMessage.UpdatedBulletsEntryR\x0eupdatedBullets\x12\\\n" +
	"\x0fremoved_bullets\x18\x06 \x03(\v23.protocol.GameStateDeltaMessage.RemovedBulletsEntryR\x0eremovedBullets\x12P\n" +
	"\vadded_walls\x18\a \x03(\v2/.protocol.GameStateDeltaMessage.AddedWallsEntryR\n" +
	"addedWalls\x12#\n" +
	"\rremoved_walls\x18\b \x03(\tR\fremovedWalls\x12V\n" +
	"\radded_enemies\x18\t \x03(\v21.protocol.GameStateDeltaMessage.AddedEnemiesEntryR\faddedEnemies\x12\\\n" +
	"\x0fupdated_enemies\x18\n" +
	" \x03(\v23.protocol.GameStateDeltaMessage.UpdatedEnemiesEntryR\x0eupdatedEnemies\x12'\n" +
	"\x0fremoved_enemies\x18\v \x03(\tR\x0eremovedEnemies\x12V\n" +
	"\radded_bonuses\x18\f \x03(\v21.protocol.GameStateDeltaMessage.AddedBonusesEntryR\faddedBonuses\x12\\\n" +
	"\x0fupdated_bonuses\x18\r \x03(\v23.protocol.GameStateDeltaMessage.UpdatedBonusesEntryR\x0eupdatedBonuses\x12'\n" +
	"\x0fremoved_bonuses\x18\x0e \x03(\tR\x0eremovedBonuses\x12P\n" +
	"\vadded_shops\x18\x0f \x03(\v2/.protocol.GameStateDeltaMessage.AddedShopsEntryR\n" +
	"addedShops\x12V\n" +
	"\rupdated_shops\x18\x10 \x03(\v21.protocol.GameStateDeltaMessage.UpdatedShopsEntryR\fupdatedShops\x12#\n" +
	"\rremoved_shops\x18\x11 \x03(\tR\fremovedShops\x12.\n" +
	"\x13added_players_shops\x18\x12 \x03(\tR\x11addedPlayersShops\x122\n" +
	"\x15removed_players_shops\x18\x13 \x03(\tR\x13removedPlayersShops\x12\x85\x01\n" +
	"\x1eupdated_other_player_positions\x18\x14 \x03(\v2@.protocol.GameStateDeltaMessage.UpdatedOtherPlayerPositionsEntryR\x1bupdatedOtherPlayerPositions\x12C\n" +
	"\x1eremoved_other_player_positions\x18\x15 \x03(\tR\x1bremovedOtherPlayerPositions\x12\x1c\n" +
	"\ttimestamp\x18\x16 \x01(\x03R\ttimestamp\x1aQ\n" +
	"\x11AddedPlayersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.protocol.PlayerR\x05value:\x028\x01\x1aY\n" +
	"\x13UpdatedPlayersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.protocol.PlayerUpdateR\x05value:\x028\x01\x1aQ\n" +
	"\x11AddedBulletsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.protocol.BulletR\x05value:\x028\x01\x1a[\n" +
	"\x13UpdatedBulletsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.protocol.PositionUpdateR\x05value:\x028\x01\x1aS\n" +
	"\x13RemovedBulletsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.protocol.BulletR\x05value:\x028\x01\x1aM\n" +
	"\x0fAddedWallsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.protocol.WallR\x05value:\x028\x01\x1aP\n" +
	"\x11AddedEnemiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.protocol.EnemyR\x05value:\x028\x01\x1aX\n" +
	"\x13UpdatedEnemiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.protocol.EnemyUpdateR\x05value:\x028\x01\x1aP\n" +
	"\x11AddedBonusesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.protocol.BonusR\x05value:\x028\x01\x1aX\n" +
	"\x13UpdatedBonusesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.protocol.BonusUpdateR\x05value:\x028\x01\x1aM\n" +
	"\x0fAddedShopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.protocol.ShopR\x05value:\x028\x01\x1aU\n" +
	"\x11UpdatedShopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.protocol.ShopUpdateR\x05value:\x028\x01\x1aa\n" +
	" UpdatedOtherPlayerPositionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.protocol.Vector2R\x05value:\x028\x01\"=\n" +
	"\x11PlayerJoinMessage\x12(\n" +
	"\x06player\x18\x01 \x01(\v2\x10.protocol.PlayerR\x06player\"1\n" +
	"\x12PlayerLeaveMessage\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"\x16\n" +
	"\x14PlayerRespawnMessage\"(\n" +
	"\fErrorMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xbc\x03\n" +
	"\vGameMessage\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.protocol.MessageTypeR\x04type\x12.\n" +
	"\x05input\x18\x03 \x01(\v2\x16.protocol.InputMessageH\x00R\x05input\x12K\n" +
	"\x10game_state_delta\x18\v \x01(\v2\x1f.protocol.GameStateDeltaMessageH\x00R\x0egameStateDelta\x12>\n" +
	"\vplayer_join\x18\x06 \x01(\v2\x1b.protocol.PlayerJoinMessageH\x00R\n" +
	"playerJoin\x12A\n" +
	"\fplayer_leave\x18\a \x01(\v2\x1c.protocol.PlayerLeaveMessageH\x00R\vplayerLeave\x12G\n" +
	"\x0eplayer_respawn\x18\b \x01(\v2\x1e.protocol.PlayerRespawnMessageH\x00R\rplayerRespawn\x12.\n" +
	"\x05error\x18\n" +
	" \x01(\v2\x16.protocol.ErrorMessageH\x00R\x05errorB\t\n" +
	"\apayload*\x8d\x01\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05INPUT\x10\x02\x12\x0e\n" +
	"\n" +
	"GAME_STATE\x10\x05\x12\x14\n" +
	"\x10GAME_STATE_DELTA\x10\v\x12\x0f\n" +
	"\vPLAYER_JOIN\x10\x06\x12\x10\n" +
	"\fPLAYER_LEAVE\x10\a\x12\x12\n" +
	"\x0ePLAYER_RESPAWN\x10\b\x12\t\n" +
	"\x05ERROR\x10\n" +
	"B7Z5github.com/besuhoff/dungeon-game-go/internal/protocolb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_messages_proto_goTypes = []any{
	(MessageType)(0),              // 0: protocol.MessageType
	(*Vector2)(nil),               // 1: protocol.Vector2
	(*InventoryItem)(nil),         // 2: protocol.InventoryItem
	(*Player)(nil),                // 3: protocol.Player
	(*Bullet)(nil),                // 4: protocol.Bullet
	(*Wall)(nil),                  // 5: protocol.Wall
	(*Enemy)(nil),                 // 6: protocol.Enemy
	(*Bonus)(nil),                 // 7: protocol.Bonus
	(*ShopItem)(nil),              // 8: protocol.ShopItem
	(*Shop)(nil),                  // 9: protocol.Shop
	(*InputMessage)(nil),          // 10: protocol.InputMessage
	(*PositionUpdate)(nil),        // 11: protocol.PositionUpdate
	(*TimersUpdate)(nil),          // 12: protocol.TimersUpdate
	(*LivesUpdate)(nil),           // 13: protocol.LivesUpdate
	(*InventoryUpdate)(nil),       // 14: protocol.InventoryUpdate
	(*ScoreUpdate)(nil),           // 15: protocol.ScoreUpdate
	(*PlayerBulletsUpdate)(nil),   // 16: protocol.PlayerBulletsUpdate
	(*PlayerUpdate)(nil),          // 17: protocol.PlayerUpdate
	(*DeletionUpdate)(nil),        // 18: protocol.DeletionUpdate
	(*EnemyUpdate)(nil),           // 19: protocol.EnemyUpdate
	(*BonusUpdate)(nil),           // 20: protocol.BonusUpdate
	(*ShopUpdate)(nil),            // 21: protocol.ShopUpdate
	(*GameStateDeltaMessage)(nil), // 22: protocol.GameStateDeltaMessage
	(*PlayerJoinMessage)(nil),     // 23: protocol.PlayerJoinMessage
	(*PlayerLeaveMessage)(nil),    // 24: protocol.PlayerLeaveMessage
	(*PlayerRespawnMessage)(nil),  // 25: protocol.PlayerRespawnMessage
	(*ErrorMessage)(nil),          // 26: protocol.ErrorMessage
	(*GameMessage)(nil),           // 27: protocol.GameMessage
	nil,                           // 28: protocol.Player.BulletsLeftByWeaponTypeEntry
	nil,                           // 29: protocol.Shop.InventoryEntry
	nil,                           // 30: protocol.InputMessage.ItemKeyEntry
	nil,                           // 31: protocol.InputMessage.PurchaseItemKeyEntry
	nil,                           // 32: protocol.PlayerBulletsUpdate.BulletsLeftByWeaponTypeEntry
	nil,                           // 33: protocol.ShopUpdate.InventoryEntry
	nil,                           // 34: protocol.GameStateDeltaMessage.AddedPlayersEntry
	nil,                           // 35: protocol.GameStateDeltaMessage.UpdatedPlayersEntry
	nil,                           // 36: protocol.GameStateDeltaMessage.AddedBulletsEntry
	nil,                           // 37: protocol.GameStateDeltaMessage.UpdatedBulletsEntry
	nil,                           // 38: protocol.GameStateDeltaMessage.RemovedBulletsEntry
	nil,                           // 39: protocol.GameStateDeltaMessage.AddedWallsEntry
	nil,                           // 40: protocol.GameStateDeltaMessage.AddedEnemiesEntry
	nil,                           // 41: protocol.GameStateDeltaMessage.UpdatedEnemiesEntry
	nil,                           // 42: protocol.GameStateDeltaMessage.AddedBonusesEntry
	nil,                           // 43: protocol.GameStateDeltaMessage.UpdatedBonusesEntry
	nil,                           // 44: protocol.GameStateDeltaMessage.AddedShopsEntry
	nil,                           // 45: protocol.GameStateDeltaMessage.UpdatedShopsEntry
	nil,                           // 46: protocol.GameStateDeltaMessage.UpdatedOtherPlayerPositionsEntry
}
var file_messages_proto_depIdxs = []int32{
	1,  // 0: protocol.Player.position:type_name -> protocol.Vector2
	1,  // 1: protocol.Player.velocity:type_name -> protocol.Vector2
	28, // 2: protocol.Player.bullets_left_by_weapon_type:type_name -> protocol.Player.BulletsLeftByWeaponTypeEntry
	2,  // 3: protocol.Player.inventory:type_name -> protocol.InventoryItem
	1,  // 4: protocol.Bullet.position:type_name -> protocol.Vector2
	1,  // 5: protocol.Bullet.velocity:type_name -> protocol.Vector2
	1,  // 6: protocol.Wall.position:type_name -> protocol.Vector2
	1,  // 7: protocol.Enemy.position:type_name -> protocol.Vector2
	1,  // 8: protocol.Bonus.position:type_name -> protocol.Vector2
	1,  // 9: protocol.Shop.position:type_name -> protocol.Vector2
	29, // 10: protocol.Shop.inventory:type_name -> protocol.Shop.InventoryEntry
	30, // 11: protocol.InputMessage.item_key:type_name -> protocol.InputMessage.ItemKeyEntry
	31, // 12: protocol.InputMessage.purchase_item_key:type_name -> protocol.InputMessage.PurchaseItemKeyEntry
	2,  // 13: protocol.InventoryUpdate.inventory:type_name -> protocol.InventoryItem
	32, // 14: protocol.PlayerBulletsUpdate.bullets_left_by_weapon_type:type_name -> protocol.PlayerBulletsUpdate.BulletsLeftByWeaponTypeEntry
	11, // 15: protocol.PlayerUpdate.position:type_name -> protocol.PositionUpdate
	12, // 16: protocol.PlayerUpdate.timers:type_name -> protocol.TimersUpdate
	13, // 17: protocol.PlayerUpdate.lives:type_name -> protocol.LivesUpdate
	14, // 18: protocol.PlayerUpdate.inventory:type_name -> protocol.InventoryUpdate
	15, // 19: protocol.PlayerUpdate.score:type_name -> protocol.ScoreUpdate
	16, // 20: protocol.PlayerUpdate.player_bullets:type_name -> protocol.PlayerBulletsUpdate
	11, // 21: protocol.EnemyUpdate.position:type_name -> protocol.PositionUpdate
	13, // 22: protocol.EnemyUpdate.lives:type_name -> protocol.LivesUpdate
	33, // 23: protocol.ShopUpdate.inventory:type_name -> protocol.ShopUpdate.InventoryEntry
	34, // 24: protocol.GameStateDeltaMessage.added_players:type_name -> protocol.GameStateDeltaMessage.AddedPlayersEntry
	35, // 25: protocol.GameStateDeltaMessage.updated_players:type_name -> protocol.GameStateDeltaMessage.UpdatedPlayersEntry
	36, // 26: protocol.GameStateDeltaMessage.added_bullets:type_name -> protocol.GameStateDeltaMessage.AddedBulletsEntry
	37, // 27: protocol.GameStateDeltaMessage.updated_bullets:type_name -> protocol.GameStateDeltaMessage.UpdatedBulletsEntry
	38, // 28: protocol.GameStateDeltaMessage.removed_bullets:type_name -> protocol.GameStateDeltaMessage.RemovedBulletsEntry
	39, // 29: protocol.GameStateDeltaMessage.added_walls:type_name -> protocol.GameStateDeltaMessage.AddedWallsEntry
	40, // 30: protocol.GameStateDeltaMessage.added_enemies:type_name -> protocol.GameStateDeltaMessage.AddedEnemiesEntry
	41, // 31: protocol.GameStateDeltaMessage.updated_enemies:type_name -> protocol.GameStateDeltaMessage.UpdatedEnemiesEntry
	42, // 32: protocol.GameStateDeltaMessage.added_bonuses:type_name -> protocol.GameStateDeltaMessage.AddedBonusesEntry
	43, // 33: protocol.GameStateDeltaMessage.updated_bonuses:type_name -> protocol.GameStateDeltaMessage.UpdatedBonusesEntry
	44, // 34: protocol.GameStateDeltaMessage.added_shops:type_name -> protocol.GameStateDeltaMessage.AddedShopsEntry
	45, // 35: protocol.GameStateDeltaMessage.updated_shops:type_name -> protocol.GameStateDeltaMessage.UpdatedShopsEntry
	46, // 36: protocol.GameStateDeltaMessage.updated_other_player_positions:type_name -> protocol.GameStateDeltaMessage.UpdatedOtherPlayerPositionsEntry
	3,  // 37: protocol.PlayerJoinMessage.player:type_name -> protocol.Player
	0,  // 38: protocol.GameMessage.type:type_name -> protocol.MessageType
	10, // 39: protocol.GameMessage.input:type_name -> protocol.InputMessage
	22, // 40: protocol.GameMessage.game_state_delta:type_name -> protocol.GameStateDeltaMessage
	23, // 41: protocol.GameMessage.player_join:type_name -> protocol.PlayerJoinMessage
	24, // 42: protocol.GameMessage.player_leave:type_name -> protocol.PlayerLeaveMessage
	25, // 43: protocol.GameMessage.player_respawn:type_name -> protocol.PlayerRespawnMessage
	26, // 44: protocol.GameMessage.error:type_name -> protocol.ErrorMessage
	8,  // 45: protocol.Shop.InventoryEntry.value:type_name -> protocol.ShopItem
	8,  // 46: protocol.ShopUpdate.InventoryEntry.value:type_name -> protocol.ShopItem
	3,  // 47: protocol.GameStateDeltaMessage.AddedPlayersEntry.value:type_name -> protocol.Player
	17, // 48: protocol.GameStateDeltaMessage.UpdatedPlayersEntry.value:type_name -> protocol.PlayerUpdate
	4,  // 49: protocol.GameStateDeltaMessage.AddedBulletsEntry.value:type_name -> protocol.Bullet
	11, // 50: protocol.GameStateDeltaMessage.UpdatedBulletsEntry.value:type_name -> protocol.PositionUpdate
	4,  // 51: protocol.GameStateDeltaMessage.RemovedBulletsEntry.value:type_name -> protocol.Bullet
	5,  // 52: protocol.GameStateDeltaMessage.AddedWallsEntry.value:type_name -> protocol.Wall
	6,  // 53: protocol.GameStateDeltaMessage.AddedEnemiesEntry.value:type_name -> protocol.Enemy
	19, // 54: protocol.GameStateDeltaMessage.UpdatedEnemiesEntry.value:type_name -> protocol.EnemyUpdate
	7,  // 55: protocol.GameStateDeltaMessage.AddedBonusesEntry.value:type_name -> protocol.Bonus
	20, // 56: protocol.GameStateDeltaMessage.UpdatedBonusesEntry.value:type_name -> protocol.BonusUpdate
	9,  // 57: protocol.GameStateDeltaMessage.AddedShopsEntry.value:type_name -> protocol.Shop
	21, // 58: protocol.GameStateDeltaMessage.UpdatedShopsEntry.value:type_name -> protocol.ShopUpdate
	1,  // 59: protocol.GameStateDeltaMessage.UpdatedOtherPlayerPositionsEntry.value:type_name -> protocol.Vector2
	60, // [60:60] is the sub-list for method output_type
	60, // [60:60] is the sub-list for method input_type
	60, // [60:60] is the sub-list for extension type_name
	60, // [60:60] is the sub-list for extension extendee
	0,  // [0:60] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[26].OneofWrappers = []any{
		(*GameMessage_Input)(nil),
		(*GameMessage_GameStateDelta)(nil),
		(*GameMessage_PlayerJoin)(nil),
		(*GameMessage_PlayerLeave)(nil),
		(*GameMessage_PlayerRespawn)(nil),
		(*GameMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
